[tool.poetry]
name = "typed-args"
version = "0.5.0"
description = ""
authors = ["SunDoge <384813529@qq.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
