[tool.poetry]
name = "typed-args"
version = "0.5.2"
description = "Parse command line arguments by defining dataclasses"
authors = ["SunDoge <384813529@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
toml = "^0.10.2"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
